# language: ruby
# rvm:
#       - 2.4.0
# before_script:
#   - bundle exec rake db:test:prepare

# before_install:
#   - pip install --user codecov
# after_success:
#   - codecov --file coverage/lcov.info --disable search


env:
  global:
    - CC_TEST_REPORTER_ID=91ccac87c493c0752e9c84e37a3631ab61ced9384ae3a042f7067816df19c846
language: ruby
rvm:
  - 2.4.0
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - bundle exec rake db:test:prepare
  - bundle exec rake db:seed
script:
  - bundle exec rspec
  - bundle exec cucumber
after_script:
  - ./cc-test-reporter after-build